<div class="wrapper">

<p><code><?php echo htmlentities('<a class="btn btn-primary">Primary</a>'); ?></code></p>
<a class="btn btn-primary">Primary</a>
<a class="btn btn-success">Success</a>
<a class="btn btn-warning">Warning</a>
<a class="btn btn-error">Error</a>

<p><code><?php echo htmlentities('<button class="btn btn-primary">Primary</button>'); ?></code></p>
<button class="btn btn-primary">Primary</button>
<button class="btn btn-success">Success</button>
<button class="btn btn-warning">Warning</button>
<button class="btn btn-error">Error</button>

</wrapper>
