
<div class="row padding-16px gap-16px">
    <div class="gm-3">
        <div class="g-panel t-rad"><p class="title">Panel Title</p><p>Empty Card</p></div>
    </div>

    <div class="gm-3">
        <div class="g-card "><img src="../logo.png"><p>Caption of the image</p></div>
    </div>

    <div class="gm-3">
        <div class="g-card ">
            <p>Table </p>
            <table class="g-table unbordered">
                <thead>
                <tr><th>Firstname</th><th>Lastname</th><th>Age</th></tr>
                </thead>
                <tr><td>Jill</td><td>Smith</td><td>50</td></tr>
                <tr><td>Eve</td><td>Jackson</td><td>94</td></tr>
                <tr><td>Jill</td><td>Smith</td><td>50</td></tr>
                <tr><td>Eve</td><td>Jackson</td><td>94</td></tr>
            </table>
        </div>
    </div>

    <div class="gm-3">
        <div class="bordered"><img src="../logo.png" style="filter: grayscale(100%)"><p>Caption of the image</p></div>
    </div>

    <div class="gm-3">
        <div class="bordered"><img src="../logo.png" ><p class="caption">Caption of the image</p></div>
    </div>

</div>
