

<form class="g-form padding-16px">
    <div class="row">
        <label class="gm-2">Text</label>
        <div class="gm-4">
            <input class="fullwidth" type="text" placeholder="Text">
            <span class="helptext">This is a helptext</span>
        </div>
    </div>
    <div class="row">
        <label class="gm-2">Email</label>
        <div class="gm-4">
            <input class="fullwidth" type="email">
            <span class="helptext">This is a helptext</span>
        </div>
    </div>
    <div class="row">
        <label class="gm-2">Password</label>
        <input class="gm-4" type="password">
    </div>
    <div class="row">
        <label class="gm-2">Date</label>
        <input class="gm-4" type="date">
    </div>
    <div class="row">
        <label class="gm-2">Datetime</label>
        <input class="gm-4" type="datetime-local">
    </div>
    <div class="row">
        <label class="gm-2">Time</label>
        <span class="g-group bordered gm-4"><span class="btn btn-white g-group-item g-square"><i class="fa fa-check"></i></span><input class=" g-group-item fullwidth" type="time"></span>
    </div>
    <div class="row">
        <label class="gm-2">Color</label>
        <input class="gm-4" type="color">
    </div>
    <div class="row">
        <label class="gm-2">Select</label>
        <select class="gm-4"><option>Option1<option>Option2<option>Option3</select>
    </div>
    <div class="row">
        <label class="gm-2">MultiSelect</label>
        <select class="gm-4" multiple><option>Option1<option>Option2<option>Option3</select>
    </div>
    <div class="row">
        <label class="gm-2" for="check1">Checkbox</label>
        <label class="g-switch gm-4"  for="check1">
            <input type="checkbox" id="check1">
            <div class="g-slider"></div>
        </label>
        <!--input type="checkbox" class="g-check" dc-on="#0f0" dc-off="red" data-on="\f205" data-off="\f204" id="check1"-->
    </div>

</form>
