<style>
#content [class*="gs-"],#content [class*="gm-"],#content [class*="gl-"] {
    float: left;
    padding: 10px;
    border: 1px solid white;
    background: red;
    color: white;
    overflow:hidden;
    height: 3em;
    opacity: 0.8;
}
#content [class*="gm-"]{background: green}
#content [class*="gl-"]{background: blueviolet}

</style>

<p>Grid for desktop</p>
<div class="row">
    <div class="gl-12">gl-12</div>
    <div class="gl-1">gl-1</div><div class="gl-11">gl-11</div>
    <div class="gl-2">gl-2</div><div class="gl-10">gl-10</div>
    <div class="gl-3">gl-3</div><div class="gl-9">gl-9</div>
    <div class="gl-4">gl-4</div><div class="gl-8">gl-8</div>
    <div class="gl-5">gl-5</div><div class="gl-7">gl-7</div>
    <div class="gl-6">gl-6</div><div class="gl-6">gl-6</div>
</div>

<p>Grid for tablets</p>
<div class="row">
    <div class="gm-12">gm-12</div>
    <div class="gm-1">gm-1</div><div class="gm-11">gm-11</div>
    <div class="gm-2">gm-2</div><div class="gm-10">gm-10</div>
    <div class="gm-3">gm-3</div><div class="gm-9">gm-9</div>
    <div class="gm-4">gm-4</div><div class="gm-8">gm-8</div>
    <div class="gm-5">gm-5</div><div class="gm-7">gm-7</div>
    <div class="gm-6">gm-6</div><div class="gm-6">gm-6</div>
</div>

<p>Grid for all devices</p>
<div class="row">
    <div class="gs-12">gs-12</div>
    <div class="gs-1">gs-1</div><div class="gs-11">gs-11</div>
    <div class="gs-2">gs-2</div><div class="gs-10">gs-10</div>
    <div class="gs-3">gs-3</div><div class="gs-9">gs-9</div>
    <div class="gs-4">gs-4</div><div class="gs-8">gs-8</div>
    <div class="gs-5">gs-5</div><div class="gs-7">gs-7</div>
    <div class="gs-6">gs-6</div><div class="gs-6">gs-6</div>
</div>
