
<p>Menu horizontal</p>
<ul class="g-nav dark-orange gm-12">
<li><a href="#">Item 1</a></li><li><a href="#">Item 2</a></li>
<li><a href="#" >Submenu <i class="fa fa-angle-down"></i></a>
    <ul>
            <li><a href="#">Item 1</a></li>
            <li><a href="#">Submenu 2</a>
                <ul><li><a href="#">Submenu 3</a>
                        <ul><li><a href="#">Item 1</a></li><li><a href="#">Item 2</a></li></ul>
                    </li><li><a href="#">Item 2</a></li></ul>
            </li>
        </ul>
    </li>
</ul>

<p>Menu vertical</p>
<ul class="g-nav vertical gs-4">
<li><a href="#">Item 1</a></li><li><a href="#">Item 2</a></li>
<li><a href="#">Submenu</a>
    <ul>
            <li><a href="#">Item 1</a></li>
            <li><a href="#">Submenu 2</a>
                <ul><li><a href="#">Submenu 3</a>
                        <ul><li><a href="#">Item 1</a></li><li><a href="#">Item 2</a></li></ul>
                    </li><li><a href="#">Item 2</a></li></ul>
            </li>
        </ul>
    </li>
</ul>
