

<p class="gs-12">Toolbar</p>
<ul class="g-toolbar gs-12">
                <li>
                    <a href="#menu-toggle" class="btn btn-default" id="menu-toggle" title="Toggle Menu"><i class="fa fa-bars"></i></a>
                </li>
                <li>
                    <a href="//localhost/gila/" class="btn btn-default" title="Homepage" target="_blank"><i class="fa fa-home"></i></a>
                </li>
                <li class="float-right">
                    User Name
                    <a href="//localhost/gila//logout">Logout</a>
                </li>

            </ul>
